#set_false_path -from * -to [get_pins {system_wrapper_inst/system_i/AXI4_CPU2PL_0/inst/AXI4_CPU2PL_v1_0_S_AXI_READ_inst/generate_read_blocks[*].slv_reg_reg[*][*]/D}]
#set_false_path -from [get_pins ro_top_inst/rg_RESET1_reg/C] -to *


create_clock -period 1.851 -name clk_RO_out_ref [get_pins {ro_top_inst/RO_ref_inst/puf_ref/out}]
create_clock -period 1.851 -name clk_RO_out_00 [get_pins {ro_top_inst/PR_module_inst1/RO_out[0]}]
create_clock -period 1.851 -name clk_RO_out_01 [get_pins {ro_top_inst/PR_module_inst1/RO_out[1]}]
create_clock -period 1.851 -name clk_RO_out_02 [get_pins {ro_top_inst/PR_module_inst1/RO_out[2]}]
create_clock -period 1.851 -name clk_RO_out_03 [get_pins {ro_top_inst/PR_module_inst1/RO_out[3]}]
create_clock -period 1.851 -name clk_RO_out_04 [get_pins {ro_top_inst/PR_module_inst1/RO_out[4]}]
create_clock -period 1.851 -name clk_RO_out_05 [get_pins {ro_top_inst/PR_module_inst1/RO_out[5]}]
create_clock -period 1.851 -name clk_RO_out_06 [get_pins {ro_top_inst/PR_module_inst1/RO_out[6]}]
create_clock -period 1.851 -name clk_RO_out_07 [get_pins {ro_top_inst/PR_module_inst1/RO_out[7]}]
create_clock -period 1.851 -name clk_RO_out_08 [get_pins {ro_top_inst/PR_module_inst1/RO_out[8]}]
create_clock -period 1.851 -name clk_RO_out_09 [get_pins {ro_top_inst/PR_module_inst1/RO_out[9]}]
create_clock -period 1.851 -name clk_RO_out_10 [get_pins {ro_top_inst/PR_module_inst1/RO_out[10]}]
create_clock -period 1.851 -name clk_RO_out_11 [get_pins {ro_top_inst/PR_module_inst1/RO_out[11]}]
create_clock -period 1.851 -name clk_RO_out_12 [get_pins {ro_top_inst/PR_module_inst1/RO_out[12]}]
create_clock -period 1.851 -name clk_RO_out_13 [get_pins {ro_top_inst/PR_module_inst1/RO_out[13]}]
create_clock -period 1.851 -name clk_RO_out_14 [get_pins {ro_top_inst/PR_module_inst1/RO_out[14]}]
create_clock -period 1.851 -name clk_RO_out_15 [get_pins {ro_top_inst/PR_module_inst1/RO_out[15]}]
create_clock -period 1.851 -name clk_RO_out_16 [get_pins {ro_top_inst/PR_module_inst1/RO_out[16]}]
create_clock -period 1.851 -name clk_RO_out_17 [get_pins {ro_top_inst/PR_module_inst1/RO_out[17]}]
create_clock -period 1.851 -name clk_RO_out_18 [get_pins {ro_top_inst/PR_module_inst1/RO_out[18]}]
create_clock -period 1.851 -name clk_RO_out_19 [get_pins {ro_top_inst/PR_module_inst1/RO_out[19]}]
create_clock -period 1.851 -name clk_RO_out_20 [get_pins {ro_top_inst/PR_module_inst1/RO_out[20]}]
create_clock -period 1.851 -name clk_RO_out_21 [get_pins {ro_top_inst/PR_module_inst1/RO_out[21]}]
create_clock -period 1.851 -name clk_RO_out_22 [get_pins {ro_top_inst/PR_module_inst1/RO_out[22]}]
create_clock -period 1.851 -name clk_RO_out_23 [get_pins {ro_top_inst/PR_module_inst1/RO_out[23]}]
create_clock -period 1.851 -name clk_RO_out_24 [get_pins {ro_top_inst/PR_module_inst1/RO_out[24]}]
create_clock -period 1.851 -name clk_RO_out_25 [get_pins {ro_top_inst/PR_module_inst1/RO_out[25]}]
create_clock -period 1.851 -name clk_RO_out_26 [get_pins {ro_top_inst/PR_module_inst1/RO_out[26]}]
create_clock -period 1.851 -name clk_RO_out_27 [get_pins {ro_top_inst/PR_module_inst1/RO_out[27]}]
create_clock -period 1.851 -name clk_RO_out_28 [get_pins {ro_top_inst/PR_module_inst1/RO_out[28]}]
create_clock -period 1.851 -name clk_RO_out_29 [get_pins {ro_top_inst/PR_module_inst1/RO_out[29]}]
create_clock -period 1.851 -name clk_RO_out_30 [get_pins {ro_top_inst/PR_module_inst1/RO_out[30]}]
create_clock -period 1.851 -name clk_RO_out_31 [get_pins {ro_top_inst/PR_module_inst1/RO_out[31]}]

set_clock_groups -name ASYNC_GROUPS -asynchronous -group [get_clocks clk_fpga_0] -group [get_clocks {clk_RO_out_ref clk_RO_out_00 clk_RO_out_01 clk_RO_out_02 clk_RO_out_03 clk_RO_out_04 clk_RO_out_05 clk_RO_out_06 clk_RO_out_07 clk_RO_out_08 clk_RO_out_09 clk_RO_out_10 clk_RO_out_11 clk_RO_out_12 clk_RO_out_13 clk_RO_out_14 clk_RO_out_15 clk_RO_out_16 clk_RO_out_17 clk_RO_out_18 clk_RO_out_19 clk_RO_out_20 clk_RO_out_21 clk_RO_out_22 clk_RO_out_23 clk_RO_out_24 clk_RO_out_25 clk_RO_out_26 clk_RO_out_27 clk_RO_out_28 clk_RO_out_29 clk_RO_out_30 clk_RO_out_31}]