# # create with the following command:
# write_bd_tcl -force -no_project_wrapper -no_ip_version cr_bd_system.tcl
# # call like:
# source -quiet D:/FPGA_PUFs/RO/pynq_fw/src/bd/cr_bd_system.tcl
# cr_bd_system ""

# Proc to create BD system
proc cr_bd_system { parentCell } {

  # CHANGE DESIGN NAME HERE
  set design_name system

  common::send_msg_id "BD_TCL-003" "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  uni-ulm.de:aherkle:AH_CPU2PL:*\
  uni-ulm.de:aherkle:AH_PL2DDR:*\
  xilinx.com:ip:axi_gpio:*\
  xilinx.com:ip:smartconnect:*\
  xilinx.com:ip:xlconcat:*\
  xilinx.com:ip:xlconstant:*\
  xilinx.com:ip:pr_decoupler:*\
  xilinx.com:ip:processing_system7:*\
  xilinx.com:ip:proc_sys_reset:*\
  xilinx.com:ip:xlslice:*\
  xilinx.com:ip:xadc_wiz:*\
  "

   set list_ips_missing ""
   common::send_msg_id "BD_TCL-006" "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_msg_id "BD_TCL-115" "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  if { $bCheckIPsPassed != 1 } {
    common::send_msg_id "BD_TCL-1003" "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_msg_id "BD_TCL-100" "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_msg_id "BD_TCL-101" "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set DDR [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddrx_rtl:1.0 DDR ]
  set FIXED_IO [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_processing_system7:fixedio_rtl:1.0 FIXED_IO ]
  set btns_4bits [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 btns_4bits ]
  set leds_4bits [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 leds_4bits ]
  set sws_4bits [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:gpio_rtl:1.0 sws_4bits ]

  # Create ports
  set data_en [ create_bd_port -dir I -type data data_en ]
  set data_in [ create_bd_port -dir I -from 31 -to 0 -type data data_in ]
  set meas_cmd [ create_bd_port -dir O -from 31 -to 0 -type data meas_cmd ]
  set meas_cooldown [ create_bd_port -dir O -from 31 -to 0 -type data meas_cooldown ]
  set meas_done [ create_bd_port -dir I meas_done ]
  set meas_heatup [ create_bd_port -dir O -from 31 -to 0 -type data meas_heatup ]
  set meas_mode [ create_bd_port -dir O -from 31 -to 0 -type data meas_mode ]
  set meas_readouts [ create_bd_port -dir O -from 31 -to 0 -type data meas_readouts ]
  set meas_time [ create_bd_port -dir O -from 31 -to 0 -type data meas_time ]
  set sys_clk0 [ create_bd_port -dir O -type clk sys_clk0 ]
  set sys_decouple [ create_bd_port -dir O sys_decouple ]
  set sys_reset [ create_bd_port -dir O -from 0 -to 0 -type rst sys_reset ]
  set sys_resetn [ create_bd_port -dir O -from 0 -to 0 -type rst sys_resetn ]
  set transfer_active [ create_bd_port -dir O -type data transfer_active ]
  set transfer_en [ create_bd_port -dir I -type data transfer_en ]

  # Create instance: AH_CPU2PL_0, and set properties
  set AH_CPU2PL_0 [ create_bd_cell -type ip -vlnv uni-ulm.de:aherkle:AH_CPU2PL AH_CPU2PL_0 ]
  set_property -dict [ list \
   CONFIG.ADVANCED_CLOCKING {false} \
   CONFIG.ENABLE_INTR {true} \
   CONFIG.ENABLE_IRQ {true} \
   CONFIG.IRQ_ACK {false} \
   CONFIG.IRQ_ENABLED {1} \
   CONFIG.READ_ACK {false} \
   CONFIG.SERIALIZE_INPUT {false} \
   CONFIG.SERIALIZE_INPUT_ENABLED {0} \
   CONFIG.SERIALIZE_OUTPUT {false} \
   CONFIG.SERIALIZE_OUTPUT_ENABLED {0} \
   CONFIG.USED_INPUTS {1} \
   CONFIG.USED_OUTPUTS {11} \
 ] $AH_CPU2PL_0

  # Create instance: AH_PL2DDR_0, and set properties
  set AH_PL2DDR_0 [ create_bd_cell -type ip -vlnv uni-ulm.de:aherkle:AH_PL2DDR AH_PL2DDR_0 ]
  set_property -dict [ list \
   CONFIG.DATA_WIDTH {32} \
   CONFIG.ENABLE_ADDRESS_INPUT {true} \
   CONFIG.ENABLE_CMD_INPUT {true} \
   CONFIG.ENABLE_DEBUG_OUTPUT {true} \
   CONFIG.ENABLE_ERROR_OUTPUT {true} \
   CONFIG.ENABLE_INFO_OUTPUT {true} \
   CONFIG.ENABLE_INTR_DONE {true} \
   CONFIG.ENABLE_INTR_SENT {true} \
   CONFIG.ENABLE_MODE_INPUT {true} \
   CONFIG.ENABLE_SAMPLES_INPUT {true} \
   CONFIG.ENABLE_TRANSFER_CONTROL {true} \
 ] $AH_PL2DDR_0

  # Create instance: axi_gpio_0, and set properties
  # set axi_gpio_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio axi_gpio_0 ]
  # set_property -dict [ list \
   # CONFIG.C_GPIO_WIDTH {4} \
   # CONFIG.GPIO_BOARD_INTERFACE {leds_4bits} \
   # CONFIG.USE_BOARD_FLOW {true} \
 # ] $axi_gpio_0

  # Create instance: axi_gpio_1, and set properties
  # set axi_gpio_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio axi_gpio_1 ]
  # set_property -dict [ list \
   # CONFIG.C_ALL_INPUTS {1} \
   # CONFIG.C_GPIO_WIDTH {4} \
   # CONFIG.GPIO_BOARD_INTERFACE {btns_4bits} \
   # CONFIG.USE_BOARD_FLOW {true} \
 # ] $axi_gpio_1

  # Create instance: axi_gpio_2, and set properties
  # set axi_gpio_2 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio axi_gpio_2 ]
  # set_property -dict [ list \
   # CONFIG.C_ALL_INPUTS {1} \
   # CONFIG.C_GPIO_WIDTH {4} \
   # CONFIG.GPIO_BOARD_INTERFACE {sws_4bits} \
   # CONFIG.USE_BOARD_FLOW {true} \
 # ] $axi_gpio_2

  # Create instance: axi_smc, and set properties
  set axi_smc [ create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect axi_smc ]
  set_property -dict [ list \
   CONFIG.NUM_SI {1} \
 ] $axi_smc

  # Create instance: concat_irq, and set properties
  set concat_irq [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat concat_irq ]
  set_property -dict [ list \
   CONFIG.NUM_PORTS {3} \
 ] $concat_irq

  # Create instance: const_32b0, and set properties
  set const_32b0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant const_32b0 ]
  set_property -dict [ list \
   CONFIG.CONST_VAL {0} \
   CONFIG.CONST_WIDTH {32} \
 ] $const_32b0

  # Create instance: pr_decoupler_0, and set properties
  set pr_decoupler_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:pr_decoupler pr_decoupler_0 ]
  set_property -dict [ list \
   CONFIG.ALL_PARAMS {HAS_AXI_LITE 1 HAS_SIGNAL_CONTROL 0 HAS_SIGNAL_STATUS 1 INTF {}} \
   CONFIG.GUI_HAS_AXI_LITE {1} \
   CONFIG.GUI_HAS_SIGNAL_CONTROL {0} \
   CONFIG.GUI_HAS_SIGNAL_STATUS {1} \
   CONFIG.GUI_INTERFACE_NAME { } \
   CONFIG.GUI_SELECT_INTERFACE {-1} \
   CONFIG.GUI_SIGNAL_DECOUPLED_0 {false} \
   CONFIG.GUI_SIGNAL_DECOUPLED_1 {false} \
   CONFIG.GUI_SIGNAL_DECOUPLED_2 {false} \
   CONFIG.GUI_SIGNAL_DECOUPLED_3 {false} \
   CONFIG.GUI_SIGNAL_DECOUPLED_4 {false} \
   CONFIG.GUI_SIGNAL_DIRECTION_0 {s} \
   CONFIG.GUI_SIGNAL_DIRECTION_1 {s} \
   CONFIG.GUI_SIGNAL_DIRECTION_2 {s} \
   CONFIG.GUI_SIGNAL_DIRECTION_3 {s} \
   CONFIG.GUI_SIGNAL_DIRECTION_4 {s} \
   CONFIG.GUI_SIGNAL_MANAGEMENT_0 {auto} \
   CONFIG.GUI_SIGNAL_MANAGEMENT_1 {auto} \
   CONFIG.GUI_SIGNAL_MANAGEMENT_2 {auto} \
   CONFIG.GUI_SIGNAL_MANAGEMENT_3 {auto} \
   CONFIG.GUI_SIGNAL_MANAGEMENT_4 {auto} \
   CONFIG.GUI_SIGNAL_PRESENT_0 {false} \
   CONFIG.GUI_SIGNAL_PRESENT_1 {false} \
   CONFIG.GUI_SIGNAL_PRESENT_2 {false} \
   CONFIG.GUI_SIGNAL_PRESENT_3 {false} \
   CONFIG.GUI_SIGNAL_PRESENT_4 {false} \
   CONFIG.GUI_SIGNAL_SELECT_0 {-1} \
   CONFIG.GUI_SIGNAL_SELECT_1 {-1} \
   CONFIG.GUI_SIGNAL_SELECT_2 {-1} \
   CONFIG.GUI_SIGNAL_SELECT_3 {-1} \
   CONFIG.GUI_SIGNAL_SELECT_4 {-1} \
   CONFIG.GUI_SIGNAL_WIDTH_0 {1} \
   CONFIG.GUI_SIGNAL_WIDTH_1 {1} \
   CONFIG.GUI_SIGNAL_WIDTH_2 {1} \
   CONFIG.GUI_SIGNAL_WIDTH_3 {1} \
   CONFIG.GUI_SIGNAL_WIDTH_4 {1} \
 ] $pr_decoupler_0

  # Create instance: processing_system7_0, and set properties
  set processing_system7_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7 processing_system7_0 ]
  
  apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 -config {make_external "FIXED_IO, DDR" apply_board_preset "1" Master "Disable" Slave "Disable" }  $processing_system7_0
  
  set property_board [get_property BOARD [current_project]]
	if {$property_board == "digilentinc.com:zybo:part0:1.0"} {
		# pynq
		set_property -dict [list CONFIG.PCW_USE_S_AXI_HP0 {1} CONFIG.PCW_USE_FABRIC_INTERRUPT {1} CONFIG.PCW_S_AXI_HP0_DATA_WIDTH {32} CONFIG.PCW_IRQ_F2P_INTR {1} CONFIG.PCW_QSPI_PERIPHERAL_ENABLE {0} CONFIG.PCW_ENET0_PERIPHERAL_ENABLE {1} CONFIG.PCW_TTC0_PERIPHERAL_ENABLE {0} CONFIG.PCW_USB0_PERIPHERAL_ENABLE {0}] $processing_system7_0
	} elseif {$property_board == "em.avnet.com:zed:part0:1.4"} {
		# zedboard
		set_property -dict [list CONFIG.PCW_USE_S_AXI_HP0 {1} CONFIG.PCW_USE_FABRIC_INTERRUPT {1} CONFIG.PCW_S_AXI_HP0_DATA_WIDTH {32} CONFIG.PCW_QSPI_PERIPHERAL_ENABLE {0} CONFIG.PCW_TTC0_PERIPHERAL_ENABLE {0} CONFIG.PCW_USB0_PERIPHERAL_ENABLE {0}] $processing_system7_0
	} elseif {$property_board == "www.digilentinc.com:pynq-z1:part0:1.0"} {
		# zybo
		set_property -dict [list CONFIG.PCW_USE_S_AXI_HP0 {1} CONFIG.PCW_USE_FABRIC_INTERRUPT {1} CONFIG.PCW_S_AXI_HP0_DATA_WIDTH {32} CONFIG.PCW_IRQ_F2P_INTR {1} CONFIG.PCW_QSPI_PERIPHERAL_ENABLE {0} CONFIG.PCW_UART0_PERIPHERAL_ENABLE {0} CONFIG.PCW_UART1_PERIPHERAL_ENABLE {1} CONFIG.PCW_USB0_PERIPHERAL_ENABLE {0}] $processing_system7_0
	} else {
		error "can't create ZYNQ PS - board not supported"
	}

  # set_property -dict [ list \
   # CONFIG.PCW_ACT_APU_PERIPHERAL_FREQMHZ {650.000000} \
   # CONFIG.PCW_ACT_CAN0_PERIPHERAL_FREQMHZ {23.8095} \
   # CONFIG.PCW_ACT_CAN1_PERIPHERAL_FREQMHZ {23.8095} \
   # CONFIG.PCW_ACT_CAN_PERIPHERAL_FREQMHZ {10.000000} \
   # CONFIG.PCW_ACT_DCI_PERIPHERAL_FREQMHZ {10.096154} \
   # CONFIG.PCW_ACT_ENET0_PERIPHERAL_FREQMHZ {125.000000} \
   # CONFIG.PCW_ACT_ENET1_PERIPHERAL_FREQMHZ {10.000000} \
   # CONFIG.PCW_ACT_FPGA0_PERIPHERAL_FREQMHZ {100.000000} \
   # CONFIG.PCW_ACT_FPGA1_PERIPHERAL_FREQMHZ {10.000000} \
   # CONFIG.PCW_ACT_FPGA2_PERIPHERAL_FREQMHZ {10.000000} \
   # CONFIG.PCW_ACT_FPGA3_PERIPHERAL_FREQMHZ {10.000000} \
   # CONFIG.PCW_ACT_I2C_PERIPHERAL_FREQMHZ {50} \
   # CONFIG.PCW_ACT_PCAP_PERIPHERAL_FREQMHZ {200.000000} \
   # CONFIG.PCW_ACT_QSPI_PERIPHERAL_FREQMHZ {10.000000} \
   # CONFIG.PCW_ACT_SDIO_PERIPHERAL_FREQMHZ {50.000000} \
   # CONFIG.PCW_ACT_SMC_PERIPHERAL_FREQMHZ {10.000000} \
   # CONFIG.PCW_ACT_SPI_PERIPHERAL_FREQMHZ {10.000000} \
   # CONFIG.PCW_ACT_TPIU_PERIPHERAL_FREQMHZ {200.000000} \
   # CONFIG.PCW_ACT_TTC0_CLK0_PERIPHERAL_FREQMHZ {108.333336} \
   # CONFIG.PCW_ACT_TTC0_CLK1_PERIPHERAL_FREQMHZ {108.333336} \
   # CONFIG.PCW_ACT_TTC0_CLK2_PERIPHERAL_FREQMHZ {108.333336} \
   # CONFIG.PCW_ACT_TTC1_CLK0_PERIPHERAL_FREQMHZ {108.333336} \
   # CONFIG.PCW_ACT_TTC1_CLK1_PERIPHERAL_FREQMHZ {108.333336} \
   # CONFIG.PCW_ACT_TTC1_CLK2_PERIPHERAL_FREQMHZ {108.333336} \
   # CONFIG.PCW_ACT_TTC_PERIPHERAL_FREQMHZ {50} \
   # CONFIG.PCW_ACT_UART_PERIPHERAL_FREQMHZ {100.000000} \
   # CONFIG.PCW_ACT_USB0_PERIPHERAL_FREQMHZ {60} \
   # CONFIG.PCW_ACT_USB1_PERIPHERAL_FREQMHZ {60} \
   # CONFIG.PCW_ACT_WDT_PERIPHERAL_FREQMHZ {108.333336} \
   # CONFIG.PCW_APU_CLK_RATIO_ENABLE {6:2:1} \
   # CONFIG.PCW_APU_PERIPHERAL_FREQMHZ {650} \
   # CONFIG.PCW_ARMPLL_CTRL_FBDIV {26} \
   # CONFIG.PCW_CAN0_BASEADDR {0xE0008000} \
   # CONFIG.PCW_CAN0_GRP_CLK_ENABLE {0} \
   # CONFIG.PCW_CAN0_HIGHADDR {0xE0008FFF} \
   # CONFIG.PCW_CAN0_PERIPHERAL_CLKSRC {External} \
   # CONFIG.PCW_CAN0_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_CAN0_PERIPHERAL_FREQMHZ {-1} \
   # CONFIG.PCW_CAN1_BASEADDR {0xE0009000} \
   # CONFIG.PCW_CAN1_GRP_CLK_ENABLE {0} \
   # CONFIG.PCW_CAN1_HIGHADDR {0xE0009FFF} \
   # CONFIG.PCW_CAN1_PERIPHERAL_CLKSRC {External} \
   # CONFIG.PCW_CAN1_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_CAN1_PERIPHERAL_FREQMHZ {-1} \
   # CONFIG.PCW_CAN_PERIPHERAL_CLKSRC {IO PLL} \
   # CONFIG.PCW_CAN_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_CAN_PERIPHERAL_DIVISOR1 {1} \
   # CONFIG.PCW_CAN_PERIPHERAL_FREQMHZ {100} \
   # CONFIG.PCW_CAN_PERIPHERAL_VALID {0} \
   # CONFIG.PCW_CLK0_FREQ {100000000} \
   # CONFIG.PCW_CLK1_FREQ {10000000} \
   # CONFIG.PCW_CLK2_FREQ {10000000} \
   # CONFIG.PCW_CLK3_FREQ {10000000} \
   # CONFIG.PCW_CORE0_FIQ_INTR {0} \
   # CONFIG.PCW_CORE0_IRQ_INTR {0} \
   # CONFIG.PCW_CORE1_FIQ_INTR {0} \
   # CONFIG.PCW_CORE1_IRQ_INTR {0} \
   # CONFIG.PCW_CPU_CPU_6X4X_MAX_RANGE {667} \
   # CONFIG.PCW_CPU_CPU_PLL_FREQMHZ {1300.000} \
   # CONFIG.PCW_CPU_PERIPHERAL_CLKSRC {ARM PLL} \
   # CONFIG.PCW_CPU_PERIPHERAL_DIVISOR0 {2} \
   # CONFIG.PCW_CRYSTAL_PERIPHERAL_FREQMHZ {50.000000} \
   # CONFIG.PCW_DCI_PERIPHERAL_CLKSRC {DDR PLL} \
   # CONFIG.PCW_DCI_PERIPHERAL_DIVISOR0 {52} \
   # CONFIG.PCW_DCI_PERIPHERAL_DIVISOR1 {2} \
   # CONFIG.PCW_DCI_PERIPHERAL_FREQMHZ {10.159} \
   # CONFIG.PCW_DDRPLL_CTRL_FBDIV {21} \
   # CONFIG.PCW_DDR_DDR_PLL_FREQMHZ {1050.000} \
   # CONFIG.PCW_DDR_HPRLPR_QUEUE_PARTITION {HPR(0)/LPR(32)} \
   # CONFIG.PCW_DDR_HPR_TO_CRITICAL_PRIORITY_LEVEL {15} \
   # CONFIG.PCW_DDR_LPR_TO_CRITICAL_PRIORITY_LEVEL {2} \
   # CONFIG.PCW_DDR_PERIPHERAL_CLKSRC {DDR PLL} \
   # CONFIG.PCW_DDR_PERIPHERAL_DIVISOR0 {2} \
   # CONFIG.PCW_DDR_PORT0_HPR_ENABLE {0} \
   # CONFIG.PCW_DDR_PORT1_HPR_ENABLE {0} \
   # CONFIG.PCW_DDR_PORT2_HPR_ENABLE {0} \
   # CONFIG.PCW_DDR_PORT3_HPR_ENABLE {0} \
   # CONFIG.PCW_DDR_RAM_BASEADDR {0x00100000} \
   # CONFIG.PCW_DDR_RAM_HIGHADDR {0x1FFFFFFF} \
   # CONFIG.PCW_DDR_WRITE_TO_CRITICAL_PRIORITY_LEVEL {2} \
   # CONFIG.PCW_DM_WIDTH {4} \
   # CONFIG.PCW_DQS_WIDTH {4} \
   # CONFIG.PCW_DQ_WIDTH {32} \
   # CONFIG.PCW_ENET0_BASEADDR {0xE000B000} \
   # CONFIG.PCW_ENET0_ENET0_IO {MIO 16 .. 27} \
   # CONFIG.PCW_ENET0_GRP_MDIO_ENABLE {0} \
   # CONFIG.PCW_ENET0_GRP_MDIO_IO {<Select>} \
   # CONFIG.PCW_ENET0_HIGHADDR {0xE000BFFF} \
   # CONFIG.PCW_ENET0_PERIPHERAL_CLKSRC {IO PLL} \
   # CONFIG.PCW_ENET0_PERIPHERAL_DIVISOR0 {8} \
   # CONFIG.PCW_ENET0_PERIPHERAL_DIVISOR1 {1} \
   # CONFIG.PCW_ENET0_PERIPHERAL_ENABLE {1} \
   # CONFIG.PCW_ENET0_PERIPHERAL_FREQMHZ {1000 Mbps} \
   # CONFIG.PCW_ENET0_RESET_ENABLE {0} \
   # CONFIG.PCW_ENET1_BASEADDR {0xE000C000} \
   # CONFIG.PCW_ENET1_GRP_MDIO_ENABLE {0} \
   # CONFIG.PCW_ENET1_HIGHADDR {0xE000CFFF} \
   # CONFIG.PCW_ENET1_PERIPHERAL_CLKSRC {IO PLL} \
   # CONFIG.PCW_ENET1_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_ENET1_PERIPHERAL_DIVISOR1 {1} \
   # CONFIG.PCW_ENET1_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_ENET1_PERIPHERAL_FREQMHZ {1000 Mbps} \
   # CONFIG.PCW_ENET1_RESET_ENABLE {0} \
   # CONFIG.PCW_ENET_RESET_ENABLE {0} \
   # CONFIG.PCW_ENET_RESET_POLARITY {Active Low} \
   # CONFIG.PCW_ENET_RESET_SELECT {<Select>} \
   # CONFIG.PCW_EN_4K_TIMER {0} \
   # CONFIG.PCW_EN_CAN0 {0} \
   # CONFIG.PCW_EN_CAN1 {0} \
   # CONFIG.PCW_EN_CLK0_PORT {1} \
   # CONFIG.PCW_EN_CLK1_PORT {0} \
   # CONFIG.PCW_EN_CLK2_PORT {0} \
   # CONFIG.PCW_EN_CLK3_PORT {0} \
   # CONFIG.PCW_EN_CLKTRIG0_PORT {0} \
   # CONFIG.PCW_EN_CLKTRIG1_PORT {0} \
   # CONFIG.PCW_EN_CLKTRIG2_PORT {0} \
   # CONFIG.PCW_EN_CLKTRIG3_PORT {0} \
   # CONFIG.PCW_EN_DDR {1} \
   # CONFIG.PCW_EN_EMIO_CAN0 {0} \
   # CONFIG.PCW_EN_EMIO_CAN1 {0} \
   # CONFIG.PCW_EN_EMIO_CD_SDIO0 {0} \
   # CONFIG.PCW_EN_EMIO_CD_SDIO1 {0} \
   # CONFIG.PCW_EN_EMIO_ENET0 {0} \
   # CONFIG.PCW_EN_EMIO_ENET1 {0} \
   # CONFIG.PCW_EN_EMIO_GPIO {0} \
   # CONFIG.PCW_EN_EMIO_I2C0 {0} \
   # CONFIG.PCW_EN_EMIO_I2C1 {0} \
   # CONFIG.PCW_EN_EMIO_MODEM_UART0 {0} \
   # CONFIG.PCW_EN_EMIO_MODEM_UART1 {0} \
   # CONFIG.PCW_EN_EMIO_PJTAG {0} \
   # CONFIG.PCW_EN_EMIO_SDIO0 {0} \
   # CONFIG.PCW_EN_EMIO_SDIO1 {0} \
   # CONFIG.PCW_EN_EMIO_SPI0 {0} \
   # CONFIG.PCW_EN_EMIO_SPI1 {0} \
   # CONFIG.PCW_EN_EMIO_SRAM_INT {0} \
   # CONFIG.PCW_EN_EMIO_TRACE {0} \
   # CONFIG.PCW_EN_EMIO_TTC0 {0} \
   # CONFIG.PCW_EN_EMIO_TTC1 {0} \
   # CONFIG.PCW_EN_EMIO_UART0 {0} \
   # CONFIG.PCW_EN_EMIO_UART1 {0} \
   # CONFIG.PCW_EN_EMIO_WDT {0} \
   # CONFIG.PCW_EN_EMIO_WP_SDIO0 {0} \
   # CONFIG.PCW_EN_EMIO_WP_SDIO1 {0} \
   # CONFIG.PCW_EN_ENET0 {1} \
   # CONFIG.PCW_EN_ENET1 {0} \
   # CONFIG.PCW_EN_GPIO {1} \
   # CONFIG.PCW_EN_I2C0 {0} \
   # CONFIG.PCW_EN_I2C1 {0} \
   # CONFIG.PCW_EN_MODEM_UART0 {0} \
   # CONFIG.PCW_EN_MODEM_UART1 {0} \
   # CONFIG.PCW_EN_PJTAG {0} \
   # CONFIG.PCW_EN_PTP_ENET0 {0} \
   # CONFIG.PCW_EN_PTP_ENET1 {0} \
   # CONFIG.PCW_EN_QSPI {0} \
   # CONFIG.PCW_EN_RST0_PORT {1} \
   # CONFIG.PCW_EN_RST1_PORT {0} \
   # CONFIG.PCW_EN_RST2_PORT {0} \
   # CONFIG.PCW_EN_RST3_PORT {0} \
   # CONFIG.PCW_EN_SDIO0 {1} \
   # CONFIG.PCW_EN_SDIO1 {0} \
   # CONFIG.PCW_EN_SMC {0} \
   # CONFIG.PCW_EN_SPI0 {0} \
   # CONFIG.PCW_EN_SPI1 {0} \
   # CONFIG.PCW_EN_TRACE {0} \
   # CONFIG.PCW_EN_TTC0 {0} \
   # CONFIG.PCW_EN_TTC1 {0} \
   # CONFIG.PCW_EN_UART0 {0} \
   # CONFIG.PCW_EN_UART1 {1} \
   # CONFIG.PCW_EN_USB0 {0} \
   # CONFIG.PCW_EN_USB1 {0} \
   # CONFIG.PCW_EN_WDT {0} \
   # CONFIG.PCW_FCLK0_PERIPHERAL_CLKSRC {IO PLL} \
   # CONFIG.PCW_FCLK0_PERIPHERAL_DIVISOR0 {5} \
   # CONFIG.PCW_FCLK0_PERIPHERAL_DIVISOR1 {2} \
   # CONFIG.PCW_FCLK1_PERIPHERAL_CLKSRC {IO PLL} \
   # CONFIG.PCW_FCLK1_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_FCLK1_PERIPHERAL_DIVISOR1 {1} \
   # CONFIG.PCW_FCLK2_PERIPHERAL_CLKSRC {IO PLL} \
   # CONFIG.PCW_FCLK2_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_FCLK2_PERIPHERAL_DIVISOR1 {1} \
   # CONFIG.PCW_FCLK3_PERIPHERAL_CLKSRC {IO PLL} \
   # CONFIG.PCW_FCLK3_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_FCLK3_PERIPHERAL_DIVISOR1 {1} \
   # CONFIG.PCW_FCLK_CLK0_BUF {TRUE} \
   # CONFIG.PCW_FCLK_CLK1_BUF {FALSE} \
   # CONFIG.PCW_FCLK_CLK2_BUF {FALSE} \
   # CONFIG.PCW_FCLK_CLK3_BUF {FALSE} \
   # CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {100} \
   # CONFIG.PCW_FPGA1_PERIPHERAL_FREQMHZ {200} \
   # CONFIG.PCW_FPGA2_PERIPHERAL_FREQMHZ {50} \
   # CONFIG.PCW_FPGA3_PERIPHERAL_FREQMHZ {50} \
   # CONFIG.PCW_FPGA_FCLK0_ENABLE {1} \
   # CONFIG.PCW_FPGA_FCLK1_ENABLE {0} \
   # CONFIG.PCW_FPGA_FCLK2_ENABLE {0} \
   # CONFIG.PCW_FPGA_FCLK3_ENABLE {0} \
   # CONFIG.PCW_GP0_EN_MODIFIABLE_TXN {1} \
   # CONFIG.PCW_GP0_NUM_READ_THREADS {4} \
   # CONFIG.PCW_GP0_NUM_WRITE_THREADS {4} \
   # CONFIG.PCW_GP1_EN_MODIFIABLE_TXN {1} \
   # CONFIG.PCW_GP1_NUM_READ_THREADS {4} \
   # CONFIG.PCW_GP1_NUM_WRITE_THREADS {4} \
   # CONFIG.PCW_GPIO_BASEADDR {0xE000A000} \
   # CONFIG.PCW_GPIO_EMIO_GPIO_ENABLE {0} \
   # CONFIG.PCW_GPIO_EMIO_GPIO_WIDTH {64} \
   # CONFIG.PCW_GPIO_HIGHADDR {0xE000AFFF} \
   # CONFIG.PCW_GPIO_MIO_GPIO_ENABLE {1} \
   # CONFIG.PCW_GPIO_MIO_GPIO_IO {MIO} \
   # CONFIG.PCW_GPIO_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_I2C0_BASEADDR {0xE0004000} \
   # CONFIG.PCW_I2C0_GRP_INT_ENABLE {0} \
   # CONFIG.PCW_I2C0_GRP_INT_IO {<Select>} \
   # CONFIG.PCW_I2C0_HIGHADDR {0xE0004FFF} \
   # CONFIG.PCW_I2C0_I2C0_IO {<Select>} \
   # CONFIG.PCW_I2C0_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_I2C0_RESET_ENABLE {0} \
   # CONFIG.PCW_I2C1_BASEADDR {0xE0005000} \
   # CONFIG.PCW_I2C1_GRP_INT_ENABLE {0} \
   # CONFIG.PCW_I2C1_HIGHADDR {0xE0005FFF} \
   # CONFIG.PCW_I2C1_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_I2C1_RESET_ENABLE {0} \
   # CONFIG.PCW_I2C_PERIPHERAL_FREQMHZ {25} \
   # CONFIG.PCW_I2C_RESET_ENABLE {0} \
   # CONFIG.PCW_I2C_RESET_POLARITY {Active Low} \
   # CONFIG.PCW_IMPORT_BOARD_PRESET {None} \
   # CONFIG.PCW_INCLUDE_ACP_TRANS_CHECK {0} \
   # CONFIG.PCW_INCLUDE_TRACE_BUFFER {0} \
   # CONFIG.PCW_IOPLL_CTRL_FBDIV {20} \
   # CONFIG.PCW_IO_IO_PLL_FREQMHZ {1000.000} \
   # CONFIG.PCW_IRQ_F2P_INTR {1} \
   # CONFIG.PCW_IRQ_F2P_MODE {DIRECT} \
   # CONFIG.PCW_MIO_0_DIRECTION {inout} \
   # CONFIG.PCW_MIO_0_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_0_PULLUP {enabled} \
   # CONFIG.PCW_MIO_0_SLEW {slow} \
   # CONFIG.PCW_MIO_10_DIRECTION {inout} \
   # CONFIG.PCW_MIO_10_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_10_PULLUP {enabled} \
   # CONFIG.PCW_MIO_10_SLEW {slow} \
   # CONFIG.PCW_MIO_11_DIRECTION {inout} \
   # CONFIG.PCW_MIO_11_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_11_PULLUP {enabled} \
   # CONFIG.PCW_MIO_11_SLEW {slow} \
   # CONFIG.PCW_MIO_12_DIRECTION {inout} \
   # CONFIG.PCW_MIO_12_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_12_PULLUP {enabled} \
   # CONFIG.PCW_MIO_12_SLEW {slow} \
   # CONFIG.PCW_MIO_13_DIRECTION {inout} \
   # CONFIG.PCW_MIO_13_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_13_PULLUP {enabled} \
   # CONFIG.PCW_MIO_13_SLEW {slow} \
   # CONFIG.PCW_MIO_14_DIRECTION {inout} \
   # CONFIG.PCW_MIO_14_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_14_PULLUP {enabled} \
   # CONFIG.PCW_MIO_14_SLEW {slow} \
   # CONFIG.PCW_MIO_15_DIRECTION {inout} \
   # CONFIG.PCW_MIO_15_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_15_PULLUP {enabled} \
   # CONFIG.PCW_MIO_15_SLEW {slow} \
   # CONFIG.PCW_MIO_16_DIRECTION {out} \
   # CONFIG.PCW_MIO_16_IOTYPE {HSTL 1.8V} \
   # CONFIG.PCW_MIO_16_PULLUP {disabled} \
   # CONFIG.PCW_MIO_16_SLEW {fast} \
   # CONFIG.PCW_MIO_17_DIRECTION {out} \
   # CONFIG.PCW_MIO_17_IOTYPE {HSTL 1.8V} \
   # CONFIG.PCW_MIO_17_PULLUP {disabled} \
   # CONFIG.PCW_MIO_17_SLEW {fast} \
   # CONFIG.PCW_MIO_18_DIRECTION {out} \
   # CONFIG.PCW_MIO_18_IOTYPE {HSTL 1.8V} \
   # CONFIG.PCW_MIO_18_PULLUP {disabled} \
   # CONFIG.PCW_MIO_18_SLEW {fast} \
   # CONFIG.PCW_MIO_19_DIRECTION {out} \
   # CONFIG.PCW_MIO_19_IOTYPE {HSTL 1.8V} \
   # CONFIG.PCW_MIO_19_PULLUP {disabled} \
   # CONFIG.PCW_MIO_19_SLEW {fast} \
   # CONFIG.PCW_MIO_1_DIRECTION {inout} \
   # CONFIG.PCW_MIO_1_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_1_PULLUP {disabled} \
   # CONFIG.PCW_MIO_1_SLEW {fast} \
   # CONFIG.PCW_MIO_20_DIRECTION {out} \
   # CONFIG.PCW_MIO_20_IOTYPE {HSTL 1.8V} \
   # CONFIG.PCW_MIO_20_PULLUP {disabled} \
   # CONFIG.PCW_MIO_20_SLEW {fast} \
   # CONFIG.PCW_MIO_21_DIRECTION {out} \
   # CONFIG.PCW_MIO_21_IOTYPE {HSTL 1.8V} \
   # CONFIG.PCW_MIO_21_PULLUP {disabled} \
   # CONFIG.PCW_MIO_21_SLEW {fast} \
   # CONFIG.PCW_MIO_22_DIRECTION {in} \
   # CONFIG.PCW_MIO_22_IOTYPE {HSTL 1.8V} \
   # CONFIG.PCW_MIO_22_PULLUP {disabled} \
   # CONFIG.PCW_MIO_22_SLEW {fast} \
   # CONFIG.PCW_MIO_23_DIRECTION {in} \
   # CONFIG.PCW_MIO_23_IOTYPE {HSTL 1.8V} \
   # CONFIG.PCW_MIO_23_PULLUP {disabled} \
   # CONFIG.PCW_MIO_23_SLEW {fast} \
   # CONFIG.PCW_MIO_24_DIRECTION {in} \
   # CONFIG.PCW_MIO_24_IOTYPE {HSTL 1.8V} \
   # CONFIG.PCW_MIO_24_PULLUP {disabled} \
   # CONFIG.PCW_MIO_24_SLEW {fast} \
   # CONFIG.PCW_MIO_25_DIRECTION {in} \
   # CONFIG.PCW_MIO_25_IOTYPE {HSTL 1.8V} \
   # CONFIG.PCW_MIO_25_PULLUP {disabled} \
   # CONFIG.PCW_MIO_25_SLEW {fast} \
   # CONFIG.PCW_MIO_26_DIRECTION {in} \
   # CONFIG.PCW_MIO_26_IOTYPE {HSTL 1.8V} \
   # CONFIG.PCW_MIO_26_PULLUP {disabled} \
   # CONFIG.PCW_MIO_26_SLEW {fast} \
   # CONFIG.PCW_MIO_27_DIRECTION {in} \
   # CONFIG.PCW_MIO_27_IOTYPE {HSTL 1.8V} \
   # CONFIG.PCW_MIO_27_PULLUP {disabled} \
   # CONFIG.PCW_MIO_27_SLEW {fast} \
   # CONFIG.PCW_MIO_28_DIRECTION {inout} \
   # CONFIG.PCW_MIO_28_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_28_PULLUP {disabled} \
   # CONFIG.PCW_MIO_28_SLEW {fast} \
   # CONFIG.PCW_MIO_29_DIRECTION {inout} \
   # CONFIG.PCW_MIO_29_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_29_PULLUP {disabled} \
   # CONFIG.PCW_MIO_29_SLEW {fast} \
   # CONFIG.PCW_MIO_2_DIRECTION {inout} \
   # CONFIG.PCW_MIO_2_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_2_PULLUP {disabled} \
   # CONFIG.PCW_MIO_2_SLEW {fast} \
   # CONFIG.PCW_MIO_30_DIRECTION {inout} \
   # CONFIG.PCW_MIO_30_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_30_PULLUP {disabled} \
   # CONFIG.PCW_MIO_30_SLEW {fast} \
   # CONFIG.PCW_MIO_31_DIRECTION {inout} \
   # CONFIG.PCW_MIO_31_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_31_PULLUP {disabled} \
   # CONFIG.PCW_MIO_31_SLEW {fast} \
   # CONFIG.PCW_MIO_32_DIRECTION {inout} \
   # CONFIG.PCW_MIO_32_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_32_PULLUP {disabled} \
   # CONFIG.PCW_MIO_32_SLEW {fast} \
   # CONFIG.PCW_MIO_33_DIRECTION {inout} \
   # CONFIG.PCW_MIO_33_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_33_PULLUP {disabled} \
   # CONFIG.PCW_MIO_33_SLEW {fast} \
   # CONFIG.PCW_MIO_34_DIRECTION {inout} \
   # CONFIG.PCW_MIO_34_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_34_PULLUP {disabled} \
   # CONFIG.PCW_MIO_34_SLEW {fast} \
   # CONFIG.PCW_MIO_35_DIRECTION {inout} \
   # CONFIG.PCW_MIO_35_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_35_PULLUP {disabled} \
   # CONFIG.PCW_MIO_35_SLEW {fast} \
   # CONFIG.PCW_MIO_36_DIRECTION {inout} \
   # CONFIG.PCW_MIO_36_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_36_PULLUP {disabled} \
   # CONFIG.PCW_MIO_36_SLEW {fast} \
   # CONFIG.PCW_MIO_37_DIRECTION {inout} \
   # CONFIG.PCW_MIO_37_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_37_PULLUP {disabled} \
   # CONFIG.PCW_MIO_37_SLEW {fast} \
   # CONFIG.PCW_MIO_38_DIRECTION {inout} \
   # CONFIG.PCW_MIO_38_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_38_PULLUP {disabled} \
   # CONFIG.PCW_MIO_38_SLEW {fast} \
   # CONFIG.PCW_MIO_39_DIRECTION {inout} \
   # CONFIG.PCW_MIO_39_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_39_PULLUP {disabled} \
   # CONFIG.PCW_MIO_39_SLEW {fast} \
   # CONFIG.PCW_MIO_3_DIRECTION {inout} \
   # CONFIG.PCW_MIO_3_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_3_PULLUP {disabled} \
   # CONFIG.PCW_MIO_3_SLEW {fast} \
   # CONFIG.PCW_MIO_40_DIRECTION {inout} \
   # CONFIG.PCW_MIO_40_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_40_PULLUP {disabled} \
   # CONFIG.PCW_MIO_40_SLEW {fast} \
   # CONFIG.PCW_MIO_41_DIRECTION {inout} \
   # CONFIG.PCW_MIO_41_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_41_PULLUP {disabled} \
   # CONFIG.PCW_MIO_41_SLEW {fast} \
   # CONFIG.PCW_MIO_42_DIRECTION {inout} \
   # CONFIG.PCW_MIO_42_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_42_PULLUP {disabled} \
   # CONFIG.PCW_MIO_42_SLEW {fast} \
   # CONFIG.PCW_MIO_43_DIRECTION {inout} \
   # CONFIG.PCW_MIO_43_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_43_PULLUP {disabled} \
   # CONFIG.PCW_MIO_43_SLEW {fast} \
   # CONFIG.PCW_MIO_44_DIRECTION {inout} \
   # CONFIG.PCW_MIO_44_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_44_PULLUP {disabled} \
   # CONFIG.PCW_MIO_44_SLEW {fast} \
   # CONFIG.PCW_MIO_45_DIRECTION {inout} \
   # CONFIG.PCW_MIO_45_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_45_PULLUP {disabled} \
   # CONFIG.PCW_MIO_45_SLEW {fast} \
   # CONFIG.PCW_MIO_46_DIRECTION {inout} \
   # CONFIG.PCW_MIO_46_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_46_PULLUP {enabled} \
   # CONFIG.PCW_MIO_46_SLEW {slow} \
   # CONFIG.PCW_MIO_47_DIRECTION {in} \
   # CONFIG.PCW_MIO_47_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_47_PULLUP {disabled} \
   # CONFIG.PCW_MIO_47_SLEW {slow} \
   # CONFIG.PCW_MIO_48_DIRECTION {out} \
   # CONFIG.PCW_MIO_48_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_48_PULLUP {disabled} \
   # CONFIG.PCW_MIO_48_SLEW {slow} \
   # CONFIG.PCW_MIO_49_DIRECTION {in} \
   # CONFIG.PCW_MIO_49_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_49_PULLUP {disabled} \
   # CONFIG.PCW_MIO_49_SLEW {slow} \
   # CONFIG.PCW_MIO_4_DIRECTION {inout} \
   # CONFIG.PCW_MIO_4_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_4_PULLUP {disabled} \
   # CONFIG.PCW_MIO_4_SLEW {fast} \
   # CONFIG.PCW_MIO_50_DIRECTION {inout} \
   # CONFIG.PCW_MIO_50_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_50_PULLUP {disabled} \
   # CONFIG.PCW_MIO_50_SLEW {slow} \
   # CONFIG.PCW_MIO_51_DIRECTION {inout} \
   # CONFIG.PCW_MIO_51_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_51_PULLUP {disabled} \
   # CONFIG.PCW_MIO_51_SLEW {slow} \
   # CONFIG.PCW_MIO_52_DIRECTION {inout} \
   # CONFIG.PCW_MIO_52_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_52_PULLUP {disabled} \
   # CONFIG.PCW_MIO_52_SLEW {slow} \
   # CONFIG.PCW_MIO_53_DIRECTION {inout} \
   # CONFIG.PCW_MIO_53_IOTYPE {LVCMOS 1.8V} \
   # CONFIG.PCW_MIO_53_PULLUP {disabled} \
   # CONFIG.PCW_MIO_53_SLEW {slow} \
   # CONFIG.PCW_MIO_5_DIRECTION {inout} \
   # CONFIG.PCW_MIO_5_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_5_PULLUP {disabled} \
   # CONFIG.PCW_MIO_5_SLEW {fast} \
   # CONFIG.PCW_MIO_6_DIRECTION {inout} \
   # CONFIG.PCW_MIO_6_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_6_PULLUP {disabled} \
   # CONFIG.PCW_MIO_6_SLEW {fast} \
   # CONFIG.PCW_MIO_7_DIRECTION {out} \
   # CONFIG.PCW_MIO_7_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_7_PULLUP {disabled} \
   # CONFIG.PCW_MIO_7_SLEW {slow} \
   # CONFIG.PCW_MIO_8_DIRECTION {out} \
   # CONFIG.PCW_MIO_8_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_8_PULLUP {disabled} \
   # CONFIG.PCW_MIO_8_SLEW {fast} \
   # CONFIG.PCW_MIO_9_DIRECTION {inout} \
   # CONFIG.PCW_MIO_9_IOTYPE {LVCMOS 3.3V} \
   # CONFIG.PCW_MIO_9_PULLUP {enabled} \
   # CONFIG.PCW_MIO_9_SLEW {slow} \
   # CONFIG.PCW_MIO_PRIMITIVE {54} \
   # CONFIG.PCW_MIO_TREE_PERIPHERALS {GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#GPIO#SD 0#UART 1#UART 1#GPIO#GPIO#GPIO#GPIO} \
   # CONFIG.PCW_MIO_TREE_SIGNALS {gpio[0]#gpio[1]#gpio[2]#gpio[3]#gpio[4]#gpio[5]#gpio[6]#gpio[7]#gpio[8]#gpio[9]#gpio[10]#gpio[11]#gpio[12]#gpio[13]#gpio[14]#gpio[15]#tx_clk#txd[0]#txd[1]#txd[2]#txd[3]#tx_ctl#rx_clk#rxd[0]#rxd[1]#rxd[2]#rxd[3]#rx_ctl#gpio[28]#gpio[29]#gpio[30]#gpio[31]#gpio[32]#gpio[33]#gpio[34]#gpio[35]#gpio[36]#gpio[37]#gpio[38]#gpio[39]#clk#cmd#data[0]#data[1]#data[2]#data[3]#gpio[46]#cd#tx#rx#gpio[50]#gpio[51]#gpio[52]#gpio[53]} \
   # CONFIG.PCW_M_AXI_GP0_ENABLE_STATIC_REMAP {0} \
   # CONFIG.PCW_M_AXI_GP0_ID_WIDTH {12} \
   # CONFIG.PCW_M_AXI_GP0_SUPPORT_NARROW_BURST {0} \
   # CONFIG.PCW_M_AXI_GP0_THREAD_ID_WIDTH {12} \
   # CONFIG.PCW_M_AXI_GP1_ENABLE_STATIC_REMAP {0} \
   # CONFIG.PCW_M_AXI_GP1_ID_WIDTH {12} \
   # CONFIG.PCW_M_AXI_GP1_SUPPORT_NARROW_BURST {0} \
   # CONFIG.PCW_M_AXI_GP1_THREAD_ID_WIDTH {12} \
   # CONFIG.PCW_NAND_CYCLES_T_AR {1} \
   # CONFIG.PCW_NAND_CYCLES_T_CLR {1} \
   # CONFIG.PCW_NAND_CYCLES_T_RC {11} \
   # CONFIG.PCW_NAND_CYCLES_T_REA {1} \
   # CONFIG.PCW_NAND_CYCLES_T_RR {1} \
   # CONFIG.PCW_NAND_CYCLES_T_WC {11} \
   # CONFIG.PCW_NAND_CYCLES_T_WP {1} \
   # CONFIG.PCW_NAND_GRP_D8_ENABLE {0} \
   # CONFIG.PCW_NAND_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_NOR_CS0_T_CEOE {1} \
   # CONFIG.PCW_NOR_CS0_T_PC {1} \
   # CONFIG.PCW_NOR_CS0_T_RC {11} \
   # CONFIG.PCW_NOR_CS0_T_TR {1} \
   # CONFIG.PCW_NOR_CS0_T_WC {11} \
   # CONFIG.PCW_NOR_CS0_T_WP {1} \
   # CONFIG.PCW_NOR_CS0_WE_TIME {0} \
   # CONFIG.PCW_NOR_CS1_T_CEOE {1} \
   # CONFIG.PCW_NOR_CS1_T_PC {1} \
   # CONFIG.PCW_NOR_CS1_T_RC {11} \
   # CONFIG.PCW_NOR_CS1_T_TR {1} \
   # CONFIG.PCW_NOR_CS1_T_WC {11} \
   # CONFIG.PCW_NOR_CS1_T_WP {1} \
   # CONFIG.PCW_NOR_CS1_WE_TIME {0} \
   # CONFIG.PCW_NOR_GRP_A25_ENABLE {0} \
   # CONFIG.PCW_NOR_GRP_CS0_ENABLE {0} \
   # CONFIG.PCW_NOR_GRP_CS1_ENABLE {0} \
   # CONFIG.PCW_NOR_GRP_SRAM_CS0_ENABLE {0} \
   # CONFIG.PCW_NOR_GRP_SRAM_CS1_ENABLE {0} \
   # CONFIG.PCW_NOR_GRP_SRAM_INT_ENABLE {0} \
   # CONFIG.PCW_NOR_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_NOR_SRAM_CS0_T_CEOE {1} \
   # CONFIG.PCW_NOR_SRAM_CS0_T_PC {1} \
   # CONFIG.PCW_NOR_SRAM_CS0_T_RC {11} \
   # CONFIG.PCW_NOR_SRAM_CS0_T_TR {1} \
   # CONFIG.PCW_NOR_SRAM_CS0_T_WC {11} \
   # CONFIG.PCW_NOR_SRAM_CS0_T_WP {1} \
   # CONFIG.PCW_NOR_SRAM_CS0_WE_TIME {0} \
   # CONFIG.PCW_NOR_SRAM_CS1_T_CEOE {1} \
   # CONFIG.PCW_NOR_SRAM_CS1_T_PC {1} \
   # CONFIG.PCW_NOR_SRAM_CS1_T_RC {11} \
   # CONFIG.PCW_NOR_SRAM_CS1_T_TR {1} \
   # CONFIG.PCW_NOR_SRAM_CS1_T_WC {11} \
   # CONFIG.PCW_NOR_SRAM_CS1_T_WP {1} \
   # CONFIG.PCW_NOR_SRAM_CS1_WE_TIME {0} \
   # CONFIG.PCW_OVERRIDE_BASIC_CLOCK {0} \
   # CONFIG.PCW_P2F_CAN0_INTR {0} \
   # CONFIG.PCW_P2F_CAN1_INTR {0} \
   # CONFIG.PCW_P2F_CTI_INTR {0} \
   # CONFIG.PCW_P2F_DMAC0_INTR {0} \
   # CONFIG.PCW_P2F_DMAC1_INTR {0} \
   # CONFIG.PCW_P2F_DMAC2_INTR {0} \
   # CONFIG.PCW_P2F_DMAC3_INTR {0} \
   # CONFIG.PCW_P2F_DMAC4_INTR {0} \
   # CONFIG.PCW_P2F_DMAC5_INTR {0} \
   # CONFIG.PCW_P2F_DMAC6_INTR {0} \
   # CONFIG.PCW_P2F_DMAC7_INTR {0} \
   # CONFIG.PCW_P2F_DMAC_ABORT_INTR {0} \
   # CONFIG.PCW_P2F_ENET0_INTR {0} \
   # CONFIG.PCW_P2F_ENET1_INTR {0} \
   # CONFIG.PCW_P2F_GPIO_INTR {0} \
   # CONFIG.PCW_P2F_I2C0_INTR {0} \
   # CONFIG.PCW_P2F_I2C1_INTR {0} \
   # CONFIG.PCW_P2F_QSPI_INTR {0} \
   # CONFIG.PCW_P2F_SDIO0_INTR {0} \
   # CONFIG.PCW_P2F_SDIO1_INTR {0} \
   # CONFIG.PCW_P2F_SMC_INTR {0} \
   # CONFIG.PCW_P2F_SPI0_INTR {0} \
   # CONFIG.PCW_P2F_SPI1_INTR {0} \
   # CONFIG.PCW_P2F_UART0_INTR {0} \
   # CONFIG.PCW_P2F_UART1_INTR {0} \
   # CONFIG.PCW_P2F_USB0_INTR {0} \
   # CONFIG.PCW_P2F_USB1_INTR {0} \
   # CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY0 {0.080} \
   # CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY1 {0.063} \
   # CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY2 {0.057} \
   # CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY3 {0.068} \
   # CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_0 {-0.047} \
   # CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_1 {-0.025} \
   # CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_2 {-0.006} \
   # CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_3 {-0.017} \
   # CONFIG.PCW_PACKAGE_NAME {clg400} \
   # CONFIG.PCW_PCAP_PERIPHERAL_CLKSRC {IO PLL} \
   # CONFIG.PCW_PCAP_PERIPHERAL_DIVISOR0 {5} \
   # CONFIG.PCW_PCAP_PERIPHERAL_FREQMHZ {200} \
   # CONFIG.PCW_PERIPHERAL_BOARD_PRESET {part0} \
   # CONFIG.PCW_PJTAG_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_PLL_BYPASSMODE_ENABLE {0} \
   # CONFIG.PCW_PRESET_BANK0_VOLTAGE {LVCMOS 3.3V} \
   # CONFIG.PCW_PRESET_BANK1_VOLTAGE {LVCMOS 1.8V} \
   # CONFIG.PCW_PS7_SI_REV {PRODUCTION} \
   # CONFIG.PCW_QSPI_GRP_FBCLK_ENABLE {0} \
   # CONFIG.PCW_QSPI_GRP_FBCLK_IO {<Select>} \
   # CONFIG.PCW_QSPI_GRP_IO1_ENABLE {0} \
   # CONFIG.PCW_QSPI_GRP_SINGLE_SS_ENABLE {0} \
   # CONFIG.PCW_QSPI_GRP_SINGLE_SS_IO {<Select>} \
   # CONFIG.PCW_QSPI_GRP_SS1_ENABLE {0} \
   # CONFIG.PCW_QSPI_INTERNAL_HIGHADDRESS {0xFCFFFFFF} \
   # CONFIG.PCW_QSPI_PERIPHERAL_CLKSRC {IO PLL} \
   # CONFIG.PCW_QSPI_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_QSPI_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_QSPI_PERIPHERAL_FREQMHZ {200} \
   # CONFIG.PCW_QSPI_QSPI_IO {<Select>} \
   # CONFIG.PCW_SD0_GRP_CD_ENABLE {1} \
   # CONFIG.PCW_SD0_GRP_CD_IO {MIO 47} \
   # CONFIG.PCW_SD0_GRP_POW_ENABLE {0} \
   # CONFIG.PCW_SD0_GRP_WP_ENABLE {0} \
   # CONFIG.PCW_SD0_GRP_WP_IO {<Select>} \
   # CONFIG.PCW_SD0_PERIPHERAL_ENABLE {1} \
   # CONFIG.PCW_SD0_SD0_IO {MIO 40 .. 45} \
   # CONFIG.PCW_SD1_GRP_CD_ENABLE {0} \
   # CONFIG.PCW_SD1_GRP_POW_ENABLE {0} \
   # CONFIG.PCW_SD1_GRP_WP_ENABLE {0} \
   # CONFIG.PCW_SD1_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_SDIO0_BASEADDR {0xE0100000} \
   # CONFIG.PCW_SDIO0_HIGHADDR {0xE0100FFF} \
   # CONFIG.PCW_SDIO1_BASEADDR {0xE0101000} \
   # CONFIG.PCW_SDIO1_HIGHADDR {0xE0101FFF} \
   # CONFIG.PCW_SDIO_PERIPHERAL_CLKSRC {IO PLL} \
   # CONFIG.PCW_SDIO_PERIPHERAL_DIVISOR0 {20} \
   # CONFIG.PCW_SDIO_PERIPHERAL_FREQMHZ {50} \
   # CONFIG.PCW_SDIO_PERIPHERAL_VALID {1} \
   # CONFIG.PCW_SINGLE_QSPI_DATA_MODE {<Select>} \
   # CONFIG.PCW_SMC_CYCLE_T0 {NA} \
   # CONFIG.PCW_SMC_CYCLE_T1 {NA} \
   # CONFIG.PCW_SMC_CYCLE_T2 {NA} \
   # CONFIG.PCW_SMC_CYCLE_T3 {NA} \
   # CONFIG.PCW_SMC_CYCLE_T4 {NA} \
   # CONFIG.PCW_SMC_CYCLE_T5 {NA} \
   # CONFIG.PCW_SMC_CYCLE_T6 {NA} \
   # CONFIG.PCW_SMC_PERIPHERAL_CLKSRC {IO PLL} \
   # CONFIG.PCW_SMC_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_SMC_PERIPHERAL_FREQMHZ {100} \
   # CONFIG.PCW_SMC_PERIPHERAL_VALID {0} \
   # CONFIG.PCW_SPI0_BASEADDR {0xE0006000} \
   # CONFIG.PCW_SPI0_GRP_SS0_ENABLE {0} \
   # CONFIG.PCW_SPI0_GRP_SS1_ENABLE {0} \
   # CONFIG.PCW_SPI0_GRP_SS2_ENABLE {0} \
   # CONFIG.PCW_SPI0_HIGHADDR {0xE0006FFF} \
   # CONFIG.PCW_SPI0_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_SPI1_BASEADDR {0xE0007000} \
   # CONFIG.PCW_SPI1_GRP_SS0_ENABLE {0} \
   # CONFIG.PCW_SPI1_GRP_SS1_ENABLE {0} \
   # CONFIG.PCW_SPI1_GRP_SS2_ENABLE {0} \
   # CONFIG.PCW_SPI1_HIGHADDR {0xE0007FFF} \
   # CONFIG.PCW_SPI1_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_SPI_PERIPHERAL_CLKSRC {IO PLL} \
   # CONFIG.PCW_SPI_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_SPI_PERIPHERAL_FREQMHZ {166.666666} \
   # CONFIG.PCW_SPI_PERIPHERAL_VALID {0} \
   # CONFIG.PCW_S_AXI_ACP_ARUSER_VAL {31} \
   # CONFIG.PCW_S_AXI_ACP_AWUSER_VAL {31} \
   # CONFIG.PCW_S_AXI_ACP_ID_WIDTH {3} \
   # CONFIG.PCW_S_AXI_GP0_ID_WIDTH {6} \
   # CONFIG.PCW_S_AXI_GP1_ID_WIDTH {6} \
   # CONFIG.PCW_S_AXI_HP0_DATA_WIDTH {32} \
   # CONFIG.PCW_S_AXI_HP0_ID_WIDTH {6} \
   # CONFIG.PCW_S_AXI_HP1_DATA_WIDTH {64} \
   # CONFIG.PCW_S_AXI_HP1_ID_WIDTH {6} \
   # CONFIG.PCW_S_AXI_HP2_DATA_WIDTH {64} \
   # CONFIG.PCW_S_AXI_HP2_ID_WIDTH {6} \
   # CONFIG.PCW_S_AXI_HP3_DATA_WIDTH {64} \
   # CONFIG.PCW_S_AXI_HP3_ID_WIDTH {6} \
   # CONFIG.PCW_TPIU_PERIPHERAL_CLKSRC {External} \
   # CONFIG.PCW_TPIU_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_TPIU_PERIPHERAL_FREQMHZ {200} \
   # CONFIG.PCW_TRACE_BUFFER_CLOCK_DELAY {12} \
   # CONFIG.PCW_TRACE_BUFFER_FIFO_SIZE {128} \
   # CONFIG.PCW_TRACE_GRP_16BIT_ENABLE {0} \
   # CONFIG.PCW_TRACE_GRP_2BIT_ENABLE {0} \
   # CONFIG.PCW_TRACE_GRP_32BIT_ENABLE {0} \
   # CONFIG.PCW_TRACE_GRP_4BIT_ENABLE {0} \
   # CONFIG.PCW_TRACE_GRP_8BIT_ENABLE {0} \
   # CONFIG.PCW_TRACE_INTERNAL_WIDTH {2} \
   # CONFIG.PCW_TRACE_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_TRACE_PIPELINE_WIDTH {8} \
   # CONFIG.PCW_TTC0_BASEADDR {0xE0104000} \
   # CONFIG.PCW_TTC0_CLK0_PERIPHERAL_CLKSRC {CPU_1X} \
   # CONFIG.PCW_TTC0_CLK0_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_TTC0_CLK0_PERIPHERAL_FREQMHZ {133.333333} \
   # CONFIG.PCW_TTC0_CLK1_PERIPHERAL_CLKSRC {CPU_1X} \
   # CONFIG.PCW_TTC0_CLK1_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_TTC0_CLK1_PERIPHERAL_FREQMHZ {133.333333} \
   # CONFIG.PCW_TTC0_CLK2_PERIPHERAL_CLKSRC {CPU_1X} \
   # CONFIG.PCW_TTC0_CLK2_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_TTC0_CLK2_PERIPHERAL_FREQMHZ {133.333333} \
   # CONFIG.PCW_TTC0_HIGHADDR {0xE0104fff} \
   # CONFIG.PCW_TTC0_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_TTC0_TTC0_IO {<Select>} \
   # CONFIG.PCW_TTC1_BASEADDR {0xE0105000} \
   # CONFIG.PCW_TTC1_CLK0_PERIPHERAL_CLKSRC {CPU_1X} \
   # CONFIG.PCW_TTC1_CLK0_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_TTC1_CLK0_PERIPHERAL_FREQMHZ {133.333333} \
   # CONFIG.PCW_TTC1_CLK1_PERIPHERAL_CLKSRC {CPU_1X} \
   # CONFIG.PCW_TTC1_CLK1_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_TTC1_CLK1_PERIPHERAL_FREQMHZ {133.333333} \
   # CONFIG.PCW_TTC1_CLK2_PERIPHERAL_CLKSRC {CPU_1X} \
   # CONFIG.PCW_TTC1_CLK2_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_TTC1_CLK2_PERIPHERAL_FREQMHZ {133.333333} \
   # CONFIG.PCW_TTC1_HIGHADDR {0xE0105fff} \
   # CONFIG.PCW_TTC1_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_TTC_PERIPHERAL_FREQMHZ {50} \
   # CONFIG.PCW_UART0_BASEADDR {0xE0000000} \
   # CONFIG.PCW_UART0_BAUD_RATE {115200} \
   # CONFIG.PCW_UART0_GRP_FULL_ENABLE {0} \
   # CONFIG.PCW_UART0_HIGHADDR {0xE0000FFF} \
   # CONFIG.PCW_UART0_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_UART1_BASEADDR {0xE0001000} \
   # CONFIG.PCW_UART1_BAUD_RATE {115200} \
   # CONFIG.PCW_UART1_GRP_FULL_ENABLE {0} \
   # CONFIG.PCW_UART1_HIGHADDR {0xE0001FFF} \
   # CONFIG.PCW_UART1_PERIPHERAL_ENABLE {1} \
   # CONFIG.PCW_UART1_UART1_IO {MIO 48 .. 49} \
   # CONFIG.PCW_UART_PERIPHERAL_CLKSRC {IO PLL} \
   # CONFIG.PCW_UART_PERIPHERAL_DIVISOR0 {10} \
   # CONFIG.PCW_UART_PERIPHERAL_FREQMHZ {100} \
   # CONFIG.PCW_UART_PERIPHERAL_VALID {1} \
   # CONFIG.PCW_UIPARAM_ACT_DDR_FREQ_MHZ {525.000000} \
   # CONFIG.PCW_UIPARAM_DDR_ADV_ENABLE {0} \
   # CONFIG.PCW_UIPARAM_DDR_AL {0} \
   # CONFIG.PCW_UIPARAM_DDR_BANK_ADDR_COUNT {3} \
   # CONFIG.PCW_UIPARAM_DDR_BL {8} \
   # CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY0 {0.176} \
   # CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY1 {0.159} \
   # CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY2 {0.162} \
   # CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY3 {0.187} \
   # CONFIG.PCW_UIPARAM_DDR_BUS_WIDTH {32 Bit} \
   # CONFIG.PCW_UIPARAM_DDR_CL {7} \
   # CONFIG.PCW_UIPARAM_DDR_CLOCK_0_LENGTH_MM {0} \
   # CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PACKAGE_LENGTH {54.563} \
   # CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PROPOGATION_DELAY {160} \
   # CONFIG.PCW_UIPARAM_DDR_CLOCK_1_LENGTH_MM {0} \
   # CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PACKAGE_LENGTH {54.563} \
   # CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PROPOGATION_DELAY {160} \
   # CONFIG.PCW_UIPARAM_DDR_CLOCK_2_LENGTH_MM {0} \
   # CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PACKAGE_LENGTH {54.563} \
   # CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PROPOGATION_DELAY {160} \
   # CONFIG.PCW_UIPARAM_DDR_CLOCK_3_LENGTH_MM {0} \
   # CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PACKAGE_LENGTH {54.563} \
   # CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PROPOGATION_DELAY {160} \
   # CONFIG.PCW_UIPARAM_DDR_CLOCK_STOP_EN {0} \
   # CONFIG.PCW_UIPARAM_DDR_COL_ADDR_COUNT {10} \
   # CONFIG.PCW_UIPARAM_DDR_CWL {6} \
   # CONFIG.PCW_UIPARAM_DDR_DEVICE_CAPACITY {2048 MBits} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_0_LENGTH_MM {0} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_0_PACKAGE_LENGTH {101.239} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_0_PROPOGATION_DELAY {160} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_1_LENGTH_MM {0} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_1_PACKAGE_LENGTH {79.5025} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_1_PROPOGATION_DELAY {160} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_2_LENGTH_MM {0} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_2_PACKAGE_LENGTH {60.536} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_2_PROPOGATION_DELAY {160} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_3_LENGTH_MM {0} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_3_PACKAGE_LENGTH {71.7715} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_3_PROPOGATION_DELAY {160} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 {-0.073} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 {-0.034} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_2 {-0.03} \
   # CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_3 {-0.082} \
   # CONFIG.PCW_UIPARAM_DDR_DQ_0_LENGTH_MM {0} \
   # CONFIG.PCW_UIPARAM_DDR_DQ_0_PACKAGE_LENGTH {104.5365} \
   # CONFIG.PCW_UIPARAM_DDR_DQ_0_PROPOGATION_DELAY {160} \
   # CONFIG.PCW_UIPARAM_DDR_DQ_1_LENGTH_MM {0} \
   # CONFIG.PCW_UIPARAM_DDR_DQ_1_PACKAGE_LENGTH {70.676} \
   # CONFIG.PCW_UIPARAM_DDR_DQ_1_PROPOGATION_DELAY {160} \
   # CONFIG.PCW_UIPARAM_DDR_DQ_2_LENGTH_MM {0} \
   # CONFIG.PCW_UIPARAM_DDR_DQ_2_PACKAGE_LENGTH {59.1615} \
   # CONFIG.PCW_UIPARAM_DDR_DQ_2_PROPOGATION_DELAY {160} \
   # CONFIG.PCW_UIPARAM_DDR_DQ_3_LENGTH_MM {0} \
   # CONFIG.PCW_UIPARAM_DDR_DQ_3_PACKAGE_LENGTH {81.319} \
   # CONFIG.PCW_UIPARAM_DDR_DQ_3_PROPOGATION_DELAY {160} \
   # CONFIG.PCW_UIPARAM_DDR_DRAM_WIDTH {16 Bits} \
   # CONFIG.PCW_UIPARAM_DDR_ECC {Disabled} \
   # CONFIG.PCW_UIPARAM_DDR_ENABLE {1} \
   # CONFIG.PCW_UIPARAM_DDR_FREQ_MHZ {525} \
   # CONFIG.PCW_UIPARAM_DDR_HIGH_TEMP {Normal (0-85)} \
   # CONFIG.PCW_UIPARAM_DDR_MEMORY_TYPE {DDR 3} \
   # CONFIG.PCW_UIPARAM_DDR_PARTNO {MT41K128M16 JT-125} \
   # CONFIG.PCW_UIPARAM_DDR_ROW_ADDR_COUNT {14} \
   # CONFIG.PCW_UIPARAM_DDR_SPEED_BIN {DDR3_1066F} \
   # CONFIG.PCW_UIPARAM_DDR_TRAIN_DATA_EYE {1} \
   # CONFIG.PCW_UIPARAM_DDR_TRAIN_READ_GATE {1} \
   # CONFIG.PCW_UIPARAM_DDR_TRAIN_WRITE_LEVEL {1} \
   # CONFIG.PCW_UIPARAM_DDR_T_FAW {40.0} \
   # CONFIG.PCW_UIPARAM_DDR_T_RAS_MIN {35.0} \
   # CONFIG.PCW_UIPARAM_DDR_T_RC {48.75} \
   # CONFIG.PCW_UIPARAM_DDR_T_RCD {7} \
   # CONFIG.PCW_UIPARAM_DDR_T_RP {7} \
   # CONFIG.PCW_UIPARAM_DDR_USE_INTERNAL_VREF {0} \
   # CONFIG.PCW_UIPARAM_GENERATE_SUMMARY {NA} \
   # CONFIG.PCW_USB0_BASEADDR {0xE0102000} \
   # CONFIG.PCW_USB0_HIGHADDR {0xE0102fff} \
   # CONFIG.PCW_USB0_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_USB0_PERIPHERAL_FREQMHZ {60} \
   # CONFIG.PCW_USB0_RESET_ENABLE {0} \
   # CONFIG.PCW_USB0_RESET_IO {<Select>} \
   # CONFIG.PCW_USB0_USB0_IO {<Select>} \
   # CONFIG.PCW_USB1_BASEADDR {0xE0103000} \
   # CONFIG.PCW_USB1_HIGHADDR {0xE0103fff} \
   # CONFIG.PCW_USB1_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_USB1_PERIPHERAL_FREQMHZ {60} \
   # CONFIG.PCW_USB1_RESET_ENABLE {0} \
   # CONFIG.PCW_USB_RESET_ENABLE {0} \
   # CONFIG.PCW_USB_RESET_POLARITY {Active Low} \
   # CONFIG.PCW_USE_AXI_FABRIC_IDLE {0} \
   # CONFIG.PCW_USE_AXI_NONSECURE {0} \
   # CONFIG.PCW_USE_CORESIGHT {0} \
   # CONFIG.PCW_USE_CROSS_TRIGGER {0} \
   # CONFIG.PCW_USE_CR_FABRIC {1} \
   # CONFIG.PCW_USE_DDR_BYPASS {0} \
   # CONFIG.PCW_USE_DEBUG {0} \
   # CONFIG.PCW_USE_DEFAULT_ACP_USER_VAL {0} \
   # CONFIG.PCW_USE_DMA0 {0} \
   # CONFIG.PCW_USE_DMA1 {0} \
   # CONFIG.PCW_USE_DMA2 {0} \
   # CONFIG.PCW_USE_DMA3 {0} \
   # CONFIG.PCW_USE_EXPANDED_IOP {0} \
   # CONFIG.PCW_USE_EXPANDED_PS_SLCR_REGISTERS {0} \
   # CONFIG.PCW_USE_FABRIC_INTERRUPT {1} \
   # CONFIG.PCW_USE_HIGH_OCM {0} \
   # CONFIG.PCW_USE_M_AXI_GP0 {1} \
   # CONFIG.PCW_USE_M_AXI_GP1 {0} \
   # CONFIG.PCW_USE_PROC_EVENT_BUS {0} \
   # CONFIG.PCW_USE_PS_SLCR_REGISTERS {0} \
   # CONFIG.PCW_USE_S_AXI_ACP {0} \
   # CONFIG.PCW_USE_S_AXI_GP0 {0} \
   # CONFIG.PCW_USE_S_AXI_GP1 {0} \
   # CONFIG.PCW_USE_S_AXI_HP0 {1} \
   # CONFIG.PCW_USE_S_AXI_HP1 {0} \
   # CONFIG.PCW_USE_S_AXI_HP2 {0} \
   # CONFIG.PCW_USE_S_AXI_HP3 {0} \
   # CONFIG.PCW_USE_TRACE {0} \
   # CONFIG.PCW_USE_TRACE_DATA_EDGE_DETECTOR {0} \
   # CONFIG.PCW_VALUE_SILVERSION {3} \
   # CONFIG.PCW_WDT_PERIPHERAL_CLKSRC {CPU_1X} \
   # CONFIG.PCW_WDT_PERIPHERAL_DIVISOR0 {1} \
   # CONFIG.PCW_WDT_PERIPHERAL_ENABLE {0} \
   # CONFIG.PCW_WDT_PERIPHERAL_FREQMHZ {133.333333} \
 # ] $processing_system7_0

  # Create instance: ps7_0_axi_periph, and set properties
  set ps7_0_axi_periph [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect ps7_0_axi_periph ]
  set_property -dict [ list \
   CONFIG.NUM_MI {8} \
 ] $ps7_0_axi_periph

  # Create instance: rst_ps7_0_100M, and set properties
  set rst_ps7_0_100M [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset rst_ps7_0_100M ]

  # Create instance: slice_cmd_end, and set properties
  set slice_cmd_end [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlslice slice_cmd_end ]
  set_property -dict [ list \
   CONFIG.DIN_FROM {0} \
   CONFIG.DIN_TO {0} \
   CONFIG.DIN_WIDTH {11} \
 ] $slice_cmd_end

  # Create instance: xadc_wiz_0, and set properties
  set xadc_wiz_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xadc_wiz xadc_wiz_0 ]
  set_property -dict [ list \
   CONFIG.ADC_OFFSET_CALIBRATION {true} \
   CONFIG.AVERAGE_ENABLE_TEMPERATURE {true} \
   CONFIG.AVERAGE_ENABLE_VCCINT {true} \
   CONFIG.CHANNEL_AVERAGING {16} \
   CONFIG.CHANNEL_ENABLE_CALIBRATION {true} \
   CONFIG.CHANNEL_ENABLE_TEMPERATURE {true} \
   CONFIG.CHANNEL_ENABLE_VCCINT {true} \
   CONFIG.CHANNEL_ENABLE_VP_VN {false} \
   CONFIG.ENABLE_VCCDDRO_ALARM {false} \
   CONFIG.ENABLE_VCCPAUX_ALARM {false} \
   CONFIG.ENABLE_VCCPINT_ALARM {false} \
   CONFIG.EXTERNAL_MUX_CHANNEL {VP_VN} \
   CONFIG.OT_ALARM {false} \
   CONFIG.SENSOR_OFFSET_CALIBRATION {true} \
   CONFIG.SEQUENCER_MODE {Continuous} \
   CONFIG.SINGLE_CHANNEL_SELECTION {TEMPERATURE} \
   CONFIG.USER_TEMP_ALARM {false} \
   CONFIG.VCCAUX_ALARM {false} \
   CONFIG.VCCINT_ALARM {false} \
   CONFIG.XADC_STARUP_SELECTION {channel_sequencer} \
 ] $xadc_wiz_0

  set_property -dict [ list \
   CONFIG.SUPPORTS_NARROW_BURST {0} \
   CONFIG.NUM_READ_OUTSTANDING {1} \
   CONFIG.NUM_WRITE_OUTSTANDING {1} \
   CONFIG.MAX_BURST_LENGTH {1} \
 ] [get_bd_intf_pins /xadc_wiz_0/s_axi_lite]

  # Create interface connections
  connect_bd_intf_net -intf_net AH_PL2DDR_1_M_AXI_OUT [get_bd_intf_pins AH_PL2DDR_0/M_AXI_OUT] [get_bd_intf_pins axi_smc/S00_AXI]
  # connect_bd_intf_net -intf_net axi_gpio_0_GPIO [get_bd_intf_ports leds_4bits] [get_bd_intf_pins axi_gpio_0/GPIO]
  # connect_bd_intf_net -intf_net axi_gpio_1_GPIO [get_bd_intf_ports btns_4bits] [get_bd_intf_pins axi_gpio_1/GPIO]
  # connect_bd_intf_net -intf_net axi_gpio_2_GPIO [get_bd_intf_ports sws_4bits] [get_bd_intf_pins axi_gpio_2/GPIO]
  connect_bd_intf_net -intf_net axi_smc_M00_AXI [get_bd_intf_pins axi_smc/M00_AXI] [get_bd_intf_pins processing_system7_0/S_AXI_HP0]
  connect_bd_intf_net -intf_net processing_system7_0_DDR [get_bd_intf_ports DDR] [get_bd_intf_pins processing_system7_0/DDR]
  connect_bd_intf_net -intf_net processing_system7_0_FIXED_IO [get_bd_intf_ports FIXED_IO] [get_bd_intf_pins processing_system7_0/FIXED_IO]
  connect_bd_intf_net -intf_net processing_system7_0_M_AXI_GP0 [get_bd_intf_pins processing_system7_0/M_AXI_GP0] [get_bd_intf_pins ps7_0_axi_periph/S00_AXI]
  connect_bd_intf_net -intf_net ps7_0_axi_periph_M00_AXI [get_bd_intf_pins ps7_0_axi_periph/M00_AXI] [get_bd_intf_pins xadc_wiz_0/s_axi_lite]
  connect_bd_intf_net -intf_net ps7_0_axi_periph_M01_AXI [get_bd_intf_pins AH_CPU2PL_0/S_AXI_WRITE] [get_bd_intf_pins ps7_0_axi_periph/M01_AXI]
  connect_bd_intf_net -intf_net ps7_0_axi_periph_M02_AXI [get_bd_intf_pins AH_CPU2PL_0/S_AXI_READ] [get_bd_intf_pins ps7_0_axi_periph/M02_AXI]
  connect_bd_intf_net -intf_net ps7_0_axi_periph_M03_AXI [get_bd_intf_pins AH_CPU2PL_0/S_AXI_INTR] [get_bd_intf_pins ps7_0_axi_periph/M03_AXI]
  connect_bd_intf_net -intf_net ps7_0_axi_periph_M04_AXI [get_bd_intf_pins pr_decoupler_0/s_axi_reg] [get_bd_intf_pins ps7_0_axi_periph/M04_AXI]
  # connect_bd_intf_net -intf_net ps7_0_axi_periph_M05_AXI [get_bd_intf_pins axi_gpio_0/S_AXI] [get_bd_intf_pins ps7_0_axi_periph/M05_AXI]
  # connect_bd_intf_net -intf_net ps7_0_axi_periph_M06_AXI [get_bd_intf_pins axi_gpio_1/S_AXI] [get_bd_intf_pins ps7_0_axi_periph/M06_AXI]
  # connect_bd_intf_net -intf_net ps7_0_axi_periph_M07_AXI [get_bd_intf_pins axi_gpio_2/S_AXI] [get_bd_intf_pins ps7_0_axi_periph/M07_AXI]

  # Create port connections
  connect_bd_net -net AH_CPU2PL_0_intr_output [get_bd_pins AH_CPU2PL_0/intr_output] [get_bd_pins slice_cmd_end/Din]
  connect_bd_net -net AH_CPU2PL_0_irq [get_bd_pins AH_CPU2PL_0/irq] [get_bd_pins concat_irq/In0]
  connect_bd_net -net AH_CPU2PL_0_output_0 [get_bd_pins AH_CPU2PL_0/output_0] [get_bd_pins AH_PL2DDR_0/cmd_in]
  connect_bd_net -net AH_CPU2PL_0_output_1 [get_bd_pins AH_CPU2PL_0/output_1] [get_bd_pins AH_PL2DDR_0/sampling_mode]
  connect_bd_net -net AH_CPU2PL_0_output_2 [get_bd_pins AH_CPU2PL_0/output_2] [get_bd_pins AH_PL2DDR_0/number_samples]
  connect_bd_net -net AH_CPU2PL_0_output_3 [get_bd_pins AH_CPU2PL_0/output_3] [get_bd_pins AH_PL2DDR_0/ddr_addr_low]
  connect_bd_net -net AH_CPU2PL_0_output_4 [get_bd_pins AH_CPU2PL_0/output_4] [get_bd_pins AH_PL2DDR_0/ddr_addr_high]
  connect_bd_net -net AH_CPU2PL_0_output_5 [get_bd_ports meas_cmd] [get_bd_pins AH_CPU2PL_0/output_5]
  connect_bd_net -net AH_CPU2PL_0_output_6 [get_bd_ports meas_mode] [get_bd_pins AH_CPU2PL_0/output_6]
  connect_bd_net -net AH_CPU2PL_0_output_7 [get_bd_ports meas_time] [get_bd_pins AH_CPU2PL_0/output_7]
  connect_bd_net -net AH_CPU2PL_0_output_8 [get_bd_ports meas_readouts] [get_bd_pins AH_CPU2PL_0/output_8]
  connect_bd_net -net AH_CPU2PL_0_output_9 [get_bd_ports meas_heatup] [get_bd_pins AH_CPU2PL_0/output_9]
  connect_bd_net -net AH_CPU2PL_0_output_10 [get_bd_ports meas_cooldown] [get_bd_pins AH_CPU2PL_0/output_10]
  connect_bd_net -net AH_PL2DDR_0_intr_done [get_bd_pins AH_PL2DDR_0/intr_done] [get_bd_pins concat_irq/In2]
  connect_bd_net -net AH_PL2DDR_0_intr_sent [get_bd_pins AH_PL2DDR_0/intr_sent] [get_bd_pins concat_irq/In1]
  connect_bd_net -net AH_PL2DDR_0_transfer_active [get_bd_ports transfer_active] [get_bd_pins AH_PL2DDR_0/transfer_active]
  connect_bd_net -net const_32b0_dout [get_bd_pins AH_CPU2PL_0/input_0] [get_bd_pins const_32b0/dout]
  connect_bd_net -net data_en_1 [get_bd_ports data_en] [get_bd_pins AH_PL2DDR_0/data_en]
  connect_bd_net -net data_in_1 [get_bd_ports data_in] [get_bd_pins AH_PL2DDR_0/data_in]
  connect_bd_net -net meas_done_1 [get_bd_ports meas_done] [get_bd_pins AH_CPU2PL_0/intr_input]
  connect_bd_net -net pr_decoupler_0_decouple_status [get_bd_ports sys_decouple] [get_bd_pins pr_decoupler_0/decouple_status]
  # connect_bd_net -net processing_system7_0_FCLK_CLK0 [get_bd_ports sys_clk0] [get_bd_pins AH_CPU2PL_0/s_axi_intr_aclk] [get_bd_pins AH_CPU2PL_0/s_axi_read_aclk] [get_bd_pins AH_CPU2PL_0/s_axi_write_aclk] [get_bd_pins AH_PL2DDR_0/clk_data] [get_bd_pins AH_PL2DDR_0/m_axi_out_aclk] [get_bd_pins axi_gpio_0/s_axi_aclk] [get_bd_pins axi_gpio_1/s_axi_aclk] [get_bd_pins axi_gpio_2/s_axi_aclk] [get_bd_pins axi_smc/aclk] [get_bd_pins pr_decoupler_0/aclk] [get_bd_pins processing_system7_0/FCLK_CLK0] [get_bd_pins processing_system7_0/M_AXI_GP0_ACLK] [get_bd_pins processing_system7_0/S_AXI_HP0_ACLK] [get_bd_pins ps7_0_axi_periph/ACLK] [get_bd_pins ps7_0_axi_periph/M00_ACLK] [get_bd_pins ps7_0_axi_periph/M01_ACLK] [get_bd_pins ps7_0_axi_periph/M02_ACLK] [get_bd_pins ps7_0_axi_periph/M03_ACLK] [get_bd_pins ps7_0_axi_periph/M04_ACLK] [get_bd_pins ps7_0_axi_periph/M05_ACLK] [get_bd_pins ps7_0_axi_periph/M06_ACLK] [get_bd_pins ps7_0_axi_periph/M07_ACLK] [get_bd_pins ps7_0_axi_periph/S00_ACLK] [get_bd_pins rst_ps7_0_100M/slowest_sync_clk] [get_bd_pins xadc_wiz_0/s_axi_aclk]
  connect_bd_net -net processing_system7_0_FCLK_CLK0 [get_bd_ports sys_clk0] [get_bd_pins AH_CPU2PL_0/s_axi_intr_aclk] [get_bd_pins AH_CPU2PL_0/s_axi_read_aclk] [get_bd_pins AH_CPU2PL_0/s_axi_write_aclk] [get_bd_pins AH_PL2DDR_0/clk_data] [get_bd_pins AH_PL2DDR_0/m_axi_out_aclk] [get_bd_pins axi_smc/aclk] [get_bd_pins pr_decoupler_0/aclk] [get_bd_pins processing_system7_0/FCLK_CLK0] [get_bd_pins processing_system7_0/M_AXI_GP0_ACLK] [get_bd_pins processing_system7_0/S_AXI_HP0_ACLK] [get_bd_pins ps7_0_axi_periph/ACLK] [get_bd_pins ps7_0_axi_periph/M00_ACLK] [get_bd_pins ps7_0_axi_periph/M01_ACLK] [get_bd_pins ps7_0_axi_periph/M02_ACLK] [get_bd_pins ps7_0_axi_periph/M03_ACLK] [get_bd_pins ps7_0_axi_periph/M04_ACLK] [get_bd_pins ps7_0_axi_periph/M05_ACLK] [get_bd_pins ps7_0_axi_periph/M06_ACLK] [get_bd_pins ps7_0_axi_periph/M07_ACLK] [get_bd_pins ps7_0_axi_periph/S00_ACLK] [get_bd_pins rst_ps7_0_100M/slowest_sync_clk] [get_bd_pins xadc_wiz_0/s_axi_aclk]
  connect_bd_net -net processing_system7_0_FCLK_RESET0_N [get_bd_pins processing_system7_0/FCLK_RESET0_N] [get_bd_pins rst_ps7_0_100M/ext_reset_in]
  # connect_bd_net -net rst_ps7_0_100M_peripheral_aresetn [get_bd_ports sys_resetn] [get_bd_pins AH_CPU2PL_0/s_axi_intr_aresetn] [get_bd_pins AH_CPU2PL_0/s_axi_read_aresetn] [get_bd_pins AH_CPU2PL_0/s_axi_write_aresetn] [get_bd_pins AH_PL2DDR_0/m_axi_out_aresetn] [get_bd_pins axi_gpio_0/s_axi_aresetn] [get_bd_pins axi_gpio_1/s_axi_aresetn] [get_bd_pins axi_gpio_2/s_axi_aresetn] [get_bd_pins axi_smc/aresetn] [get_bd_pins pr_decoupler_0/s_axi_reg_aresetn] [get_bd_pins ps7_0_axi_periph/ARESETN] [get_bd_pins ps7_0_axi_periph/M00_ARESETN] [get_bd_pins ps7_0_axi_periph/M01_ARESETN] [get_bd_pins ps7_0_axi_periph/M02_ARESETN] [get_bd_pins ps7_0_axi_periph/M03_ARESETN] [get_bd_pins ps7_0_axi_periph/M04_ARESETN] [get_bd_pins ps7_0_axi_periph/M05_ARESETN] [get_bd_pins ps7_0_axi_periph/M06_ARESETN] [get_bd_pins ps7_0_axi_periph/M07_ARESETN] [get_bd_pins ps7_0_axi_periph/S00_ARESETN] [get_bd_pins rst_ps7_0_100M/peripheral_aresetn] [get_bd_pins xadc_wiz_0/s_axi_aresetn]
  connect_bd_net -net rst_ps7_0_100M_peripheral_aresetn [get_bd_ports sys_resetn] [get_bd_pins AH_CPU2PL_0/s_axi_intr_aresetn] [get_bd_pins AH_CPU2PL_0/s_axi_read_aresetn] [get_bd_pins AH_CPU2PL_0/s_axi_write_aresetn] [get_bd_pins AH_PL2DDR_0/m_axi_out_aresetn] [get_bd_pins axi_smc/aresetn] [get_bd_pins pr_decoupler_0/s_axi_reg_aresetn] [get_bd_pins ps7_0_axi_periph/ARESETN] [get_bd_pins ps7_0_axi_periph/M00_ARESETN] [get_bd_pins ps7_0_axi_periph/M01_ARESETN] [get_bd_pins ps7_0_axi_periph/M02_ARESETN] [get_bd_pins ps7_0_axi_periph/M03_ARESETN] [get_bd_pins ps7_0_axi_periph/M04_ARESETN] [get_bd_pins ps7_0_axi_periph/M05_ARESETN] [get_bd_pins ps7_0_axi_periph/M06_ARESETN] [get_bd_pins ps7_0_axi_periph/M07_ARESETN] [get_bd_pins ps7_0_axi_periph/S00_ARESETN] [get_bd_pins rst_ps7_0_100M/peripheral_aresetn] [get_bd_pins xadc_wiz_0/s_axi_aresetn]
  connect_bd_net -net rst_ps7_0_100M_peripheral_reset [get_bd_ports sys_reset] [get_bd_pins rst_ps7_0_100M/peripheral_reset]
  connect_bd_net -net transfer_en_1 [get_bd_ports transfer_en] [get_bd_pins AH_PL2DDR_0/transfer_en]
  connect_bd_net -net xlconcat_0_dout [get_bd_pins concat_irq/dout] [get_bd_pins processing_system7_0/IRQ_F2P]
  connect_bd_net -net xlslice_2_Dout [get_bd_pins AH_PL2DDR_0/cmd_en] [get_bd_pins slice_cmd_end/Dout]

  # Create address segments
  create_bd_addr_seg -range 0x20000000 -offset 0x00000000 [get_bd_addr_spaces AH_PL2DDR_0/M_AXI_OUT] [get_bd_addr_segs processing_system7_0/S_AXI_HP0/HP0_DDR_LOWOCM] SEG_processing_system7_0_HP0_DDR_LOWOCM
  create_bd_addr_seg -range 0x00010000 -offset 0x43C30000 [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs AH_CPU2PL_0/S_AXI_INTR/S_AXI_INTR_reg] SEG_AH_CPU2PL_0_S_AXI_INTR_reg
  create_bd_addr_seg -range 0x00010000 -offset 0x43C20000 [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs AH_CPU2PL_0/S_AXI_READ/S_AXI_READ_reg] SEG_AH_CPU2PL_0_S_AXI_READ_reg
  create_bd_addr_seg -range 0x00010000 -offset 0x43C10000 [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs AH_CPU2PL_0/S_AXI_WRITE/S_AXI_WRITE_reg] SEG_AH_CPU2PL_0_S_AXI_WRITE_reg
  # create_bd_addr_seg -range 0x00010000 -offset 0x41200000 [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs axi_gpio_0/S_AXI/Reg] SEG_axi_gpio_0_Reg
  # create_bd_addr_seg -range 0x00010000 -offset 0x41210000 [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs axi_gpio_1/S_AXI/Reg] SEG_axi_gpio_1_Reg
  # create_bd_addr_seg -range 0x00010000 -offset 0x41220000 [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs axi_gpio_2/S_AXI/Reg] SEG_axi_gpio_2_Reg
  create_bd_addr_seg -range 0x00010000 -offset 0x43C40000 [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs pr_decoupler_0/s_axi_reg/Reg] SEG_pr_decoupler_0_Reg
  create_bd_addr_seg -range 0x00010000 -offset 0x43C00000 [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs xadc_wiz_0/s_axi_lite/Reg] SEG_xadc_wiz_0_Reg


  # Restore current instance
  current_bd_instance $oldCurInst

  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_system()